import type { PlantPreset } from '../src/lib/plants'
import { defaultCustomPlantPreset } from '../src/lib/plants'

const herbCycle = { seedDormancyDays: 5, germinationDays: 7, seedlingDevelopmentDays: 12, vegetativeGrowthDays: 28, floweringReproductionDays: 18, maturitySenescenceDays: 14 }
const leafyCycle = { seedDormancyDays: 3, germinationDays: 6, seedlingDevelopmentDays: 10, vegetativeGrowthDays: 24, floweringReproductionDays: 16, maturitySenescenceDays: 12 }
const fruitingCycle = { seedDormancyDays: 7, germinationDays: 10, seedlingDevelopmentDays: 16, vegetativeGrowthDays: 42, floweringReproductionDays: 34, maturitySenescenceDays: 24 }
const houseplantCycle = { seedDormancyDays: 14, germinationDays: 18, seedlingDevelopmentDays: 24, vegetativeGrowthDays: 120, floweringReproductionDays: 45, maturitySenescenceDays: 40 }
const flowerCycle = { seedDormancyDays: 6, germinationDays: 8, seedlingDevelopmentDays: 14, vegetativeGrowthDays: 30, floweringReproductionDays: 26, maturitySenescenceDays: 18 }
const microgreenCycle = { seedDormancyDays: 2, germinationDays: 4, seedlingDevelopmentDays: 7, vegetativeGrowthDays: 10, floweringReproductionDays: 6, maturitySenescenceDays: 5 }

export const plantCatalogSeed: PlantPreset[] = [
  { key: 'basil', name: 'Sweet Basil', species: 'Ocimum basilicum', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=1200&q=80', description: 'Fast-growing kitchen herb with strong regrowth after trimming.', location: 'Kitchen', category: 'herb', difficulty: 'easy', wateringThreshold: 34, lightingThreshold: 28, lifecycleProfile: herbCycle },
  { key: 'mint', name: 'Spearmint', species: 'Mentha spicata', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1628557044797-f21a177c37ec?auto=format&fit=crop&w=1200&q=80', description: 'Vigorous herb that likes reliable moisture and frequent pruning.', location: 'Kitchen', category: 'herb', difficulty: 'easy', wateringThreshold: 38, lightingThreshold: 26, lifecycleProfile: herbCycle },
  { key: 'cilantro', name: 'Cilantro', species: 'Coriandrum sativum', growthStage: 'seedling_development', image: 'https://images.unsplash.com/photo-1615484477778-ca3b77940c25?auto=format&fit=crop&w=1200&q=80', description: 'Short-cycle herb that prefers cooler roots and moderate light.', location: 'Kitchen', category: 'herb', difficulty: 'medium', wateringThreshold: 36, lightingThreshold: 24, lifecycleProfile: herbCycle },
  { key: 'rosemary', name: 'Rosemary', species: 'Salvia rosmarinus', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1200&q=80', description: 'Woody herb that prefers brighter light and slightly drier media.', location: 'Kitchen', category: 'herb', difficulty: 'medium', wateringThreshold: 28, lightingThreshold: 38, lifecycleProfile: herbCycle },
  { key: 'thyme', name: 'English Thyme', species: 'Thymus vulgaris', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=1200&q=80', description: 'Compact Mediterranean herb with low water demand.', location: 'Window', category: 'herb', difficulty: 'medium', wateringThreshold: 26, lightingThreshold: 36, lifecycleProfile: herbCycle },
  { key: 'oregano', name: 'Greek Oregano', species: 'Origanum vulgare', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1498579150354-977475b7ea0b?auto=format&fit=crop&w=1200&q=80', description: 'Aromatic herb that likes bright light and lean feeding.', location: 'Window', category: 'herb', difficulty: 'easy', wateringThreshold: 30, lightingThreshold: 34, lifecycleProfile: herbCycle },
  { key: 'lettuce', name: 'Butterhead Lettuce', species: 'Lactuca sativa', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1622205313162-be1d5712a43c?auto=format&fit=crop&w=1200&q=80', description: 'Compact leafy growth suited for indoor pods.', location: 'Dining Area', category: 'leafy', difficulty: 'easy', wateringThreshold: 40, lightingThreshold: 24, lifecycleProfile: leafyCycle },
  { key: 'kale', name: 'Baby Kale', species: 'Brassica oleracea var. sabellica', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1200&q=80', description: 'Dense greens with strong regrowth after harvest.', location: 'Pantry', category: 'leafy', difficulty: 'easy', wateringThreshold: 38, lightingThreshold: 26, lifecycleProfile: leafyCycle },
  { key: 'spinach', name: 'Baby Spinach', species: 'Spinacia oleracea', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=1200&q=80', description: 'Cool-loving leafy crop with fast turnover.', location: 'Pantry', category: 'leafy', difficulty: 'easy', wateringThreshold: 42, lightingThreshold: 22, lifecycleProfile: leafyCycle },
  { key: 'bokchoy', name: 'Baby Bok Choy', species: 'Brassica rapa subsp. chinensis', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80', description: 'Crisp stems and leafy tops for dense indoor production.', location: 'Dining Area', category: 'leafy', difficulty: 'easy', wateringThreshold: 39, lightingThreshold: 25, lifecycleProfile: leafyCycle },
  { key: 'arugula', name: 'Arugula', species: 'Eruca vesicaria', growthStage: 'seedling_development', image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80', description: 'Peppery greens with a very fast seed-to-harvest rhythm.', location: 'Kitchen', category: 'leafy', difficulty: 'easy', wateringThreshold: 37, lightingThreshold: 24, lifecycleProfile: leafyCycle },
  { key: 'tomato', name: 'Cherry Tomato', species: 'Solanum lycopersicum var. cerasiforme', growthStage: 'flowering_reproduction', image: 'https://images.unsplash.com/photo-1461354464878-ad92f492a5a0?auto=format&fit=crop&w=1200&q=80', description: 'A productive fruiting plant for sunnier setups.', location: 'Balcony', category: 'fruiting', difficulty: 'advanced', wateringThreshold: 36, lightingThreshold: 42, lifecycleProfile: fruitingCycle },
  { key: 'pepper', name: 'Mini Bell Pepper', species: 'Capsicum annuum', growthStage: 'flowering_reproduction', image: 'https://images.unsplash.com/photo-1518977956812-cd3dbadaaf31?auto=format&fit=crop&w=1200&q=80', description: 'Compact fruiting pepper with higher light demand.', location: 'Balcony', category: 'fruiting', difficulty: 'advanced', wateringThreshold: 35, lightingThreshold: 40, lifecycleProfile: fruitingCycle },
  { key: 'strawberry', name: 'Alpine Strawberry', species: 'Fragaria vesca', growthStage: 'flowering_reproduction', image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=1200&q=80', description: 'Compact berries with fragrant blossoms.', location: 'Window', category: 'fruiting', difficulty: 'medium', wateringThreshold: 37, lightingThreshold: 34, lifecycleProfile: fruitingCycle },
  { key: 'cucumber', name: 'Mini Cucumber', species: 'Cucumis sativus', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1566486189376-d5c9ea3c9e3e?auto=format&fit=crop&w=1200&q=80', description: 'Fast vining crop that likes strong moisture and light.', location: 'Balcony', category: 'fruiting', difficulty: 'advanced', wateringThreshold: 43, lightingThreshold: 40, lifecycleProfile: fruitingCycle },
  { key: 'eggplant', name: 'Patio Eggplant', species: 'Solanum melongena', growthStage: 'flowering_reproduction', image: 'https://images.unsplash.com/photo-1603048719537-9ecb7df1d7c4?auto=format&fit=crop&w=1200&q=80', description: 'Compact fruiting cultivar that rewards stable warmth.', location: 'Balcony', category: 'fruiting', difficulty: 'advanced', wateringThreshold: 35, lightingThreshold: 42, lifecycleProfile: fruitingCycle },
  { key: 'monstera', name: 'Monstera Deliciosa', species: 'Monstera deliciosa', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=1200&q=80', description: 'Tropical foliage plant that loves stable humidity.', location: 'Living Room', category: 'houseplant', difficulty: 'medium', wateringThreshold: 35, lightingThreshold: 30, lifecycleProfile: houseplantCycle },
  { key: 'pothos', name: 'Golden Pothos', species: 'Epipremnum aureum', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1604762524889-3e2fcc145683?auto=format&fit=crop&w=1200&q=80', description: 'Low-maintenance trailing plant for beginners.', location: 'Bedroom', category: 'houseplant', difficulty: 'easy', wateringThreshold: 32, lightingThreshold: 22, lifecycleProfile: houseplantCycle },
  { key: 'peace_lily', name: 'Peace Lily', species: 'Spathiphyllum wallisii', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1593691509543-c55fb32b0dcb?auto=format&fit=crop&w=1200&q=80', description: 'Humidity-loving foliage plant with occasional blooms.', location: 'Living Room', category: 'houseplant', difficulty: 'medium', wateringThreshold: 40, lightingThreshold: 20, lifecycleProfile: houseplantCycle },
  { key: 'snake_plant', name: 'Snake Plant', species: 'Dracaena trifasciata', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1620121478247-ec786b9be2fa?auto=format&fit=crop&w=1200&q=80', description: 'Slow-growing architectural plant that tolerates dry spells.', location: 'Bedroom', category: 'houseplant', difficulty: 'easy', wateringThreshold: 24, lightingThreshold: 18, lifecycleProfile: houseplantCycle },
  { key: 'marigold', name: 'French Marigold', species: 'Tagetes patula', growthStage: 'flowering_reproduction', image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=1200&q=80', description: 'Bright blooms with a compact indoor-friendly habit.', location: 'Window', category: 'flower', difficulty: 'easy', wateringThreshold: 33, lightingThreshold: 34, lifecycleProfile: flowerCycle },
  { key: 'petunia', name: 'Petunia', species: 'Petunia x hybrida', growthStage: 'flowering_reproduction', image: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=1200&q=80', description: 'Long-blooming annual that loves extended lighting.', location: 'Window', category: 'flower', difficulty: 'medium', wateringThreshold: 34, lightingThreshold: 36, lifecycleProfile: flowerCycle },
  { key: 'sunflower_dwarf', name: 'Dwarf Sunflower', species: 'Helianthus annuus', growthStage: 'vegetative_growth', image: 'https://images.unsplash.com/photo-1470509037663-253afd7f0f51?auto=format&fit=crop&w=1200&q=80', description: 'Compact sunflower for brighter pods and cheerful blooms.', location: 'Balcony', category: 'flower', difficulty: 'medium', wateringThreshold: 32, lightingThreshold: 44, lifecycleProfile: flowerCycle },
  { key: 'radish_microgreen', name: 'Radish Microgreens', species: 'Raphanus sativus', growthStage: 'germination', image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80', description: 'Ultra-fast microgreen cycle with spicy young shoots.', location: 'Kitchen', category: 'microgreen', difficulty: 'easy', wateringThreshold: 45, lightingThreshold: 20, lifecycleProfile: microgreenCycle },
  { key: 'broccoli_microgreen', name: 'Broccoli Microgreens', species: 'Brassica oleracea var. italica', growthStage: 'germination', image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=80', description: 'Dense trays of nutrient-rich baby greens.', location: 'Kitchen', category: 'microgreen', difficulty: 'easy', wateringThreshold: 44, lightingThreshold: 18, lifecycleProfile: microgreenCycle },
  { key: 'custom', name: 'Custom Plant', species: 'Your own variety', growthStage: defaultCustomPlantPreset.growthStage, image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&w=1200&q=80', description: 'Use your own species, threshold targets, and lifecycle estimates.', location: 'Home', category: 'houseplant', difficulty: 'medium', wateringThreshold: defaultCustomPlantPreset.wateringThreshold, lightingThreshold: defaultCustomPlantPreset.lightingThreshold, lifecycleProfile: defaultCustomPlantPreset.lifecycleProfile },
]
